### ISSUE TITLE
Windows 10 - RuntimeError: Event loop is closed and UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by pybokeh** [Voyz/databay#3]
Not a bug, but perhaps it should be mentioned that databay will not work with Windows 10 due to a bug or the way asyncio chooses the default event loop [mechanism](https://docs.python.org/3/library/asyncio-policy.html#asyncio.DefaultEventLoopPolicy), which throws an error, instead of just a warning.

So if running asyncio-dependent code on Windows machine, you will get an error similar below:

```
Traceback (most recent call last):
  File "C:\Programs\Python38\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "C:\Programs\Python38\lib\asyncio\proactor_events.py", line 86, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Programs\Python38\lib\asyncio\base_events.py", line 683, in call_soon
    self._check_closed()
  File "C:\Programs\Python38\lib\asyncio\base_events.py", line 475, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Per this SO [question](https://stackoverflow.com/questions/61610684/runtimeerror-event-loop-is-closed-on-windows), possible workaround is to use asyncio loop's ```run_until_complete()``` instead of just ```run()```

----

(Update 1 by Voy - added more info)

**To Reproduce**
Example code (blockchain example):
```
import datetime

from databay.inlets import HttpInlet
from databay.outlets import PrintOutlet
from databay import Link
from databay.planners import APSPlanner

stock_inlet = HttpInlet('https://blockchain.info/ticker')

print_outlet = PrintOutlet(True, True)

link = Link(stock_inlet, print_outlet, interval=datetime.timedelta(seconds=1))

planner = APSPlanner(link)

planner.start()
```

**Environment**
Databay version: 0.1.2
Python version: 3.8.2
OS: Ubuntu 20.04 and Windows 10

----

(Update 2 by Voy - explaining the true issue)

The `RuntimeError: Event loop is closed` is only half of the problem here, and in fact is not the cause for the code to stop working, but a side effect happening when program terminates and can be [fixed easily][2]. The code wouldn't execute due to `UnicodeEncodeError`, which [we figure out later down the line][1].

[1]: https://github.com/Voyz/databay/issues/3#issuecomment-678794806
[2]: https://github.com/Voyz/databay/issues/3#issuecomment-678427726

**Comment by pybokeh** [comment]
@Voyz Well good news!  Finally, got the blockchain_demo.py working.

Added:
```
import sys
import asyncio

if sys.version_info[0] == 3 and sys.version_info[1] >= 8 and sys.platform.startswith('win'):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
to the top of my local copy of config.py

and then at the terminal, executed:
```
chcp 65001
set PYTHONIOENCODING=utf-8
```

Then executed the blockchain_demo.py:
```
D:\Python38\envs\streaming_dev
(streaming_dev) λ python -m pdb blockchain_demo.py
> d:\python38\envs\streaming_dev\blockchain_demo.py(2)<module>()
-> import datetime
(Pdb) c
> d:\python38\envs\streaming_dev\lib\site-packages\databay\planners\aps_planner.py(134)_start_planner()
-> self._scheduler.start()
(Pdb) c
{'USD': {'15m': 11616.04, 'last': 11616.04, 'buy': 11616.04, 'sell': 11616.04, 'symbol': '$'}, 'AUD': {'15m': 16205.74, 'last': 16205.74, 'buy': 16205.74, 'sell': 16205.74, 'symbol': '$'}, 'BRL': {'15m': 65301.28, 'last': 65301.28, 'buy': 65301.28, 'sell': 65301.28, 'symbol': 'R$'}, 'CAD': {'15m': 15303.79, 'last': 15303.79, 'buy': 15303.79, 'sell': 15303.79, 'symbol': '$'}, 'CHF': {'15m': 10588.28, 'last': 10588.28, 'buy': 10588.28, 'sell': 10588.28, 'symbol': 'CHF'}, 'CLP': {'15m': 9212683.9, 'last': 9212683.9, 'buy': 9212683.9, 'sell': 9212683.9, 'symbol': '$'}, 'CNY': {'15m': 80377.21, 'last': 80377.21, 'buy': 80377.21, 'sell': 80377.21, 'symbol': '¥'}, 'DKK': {'15m': 73255.41, 'last': 73255.41, 'buy': 73255.41, 'sell': 73255.41, 'symbol': 'kr'}, 'EUR': {'15m': 9864.6, 'last': 9864.6, 'buy': 9864.6, 'sell': 9864.6, 'symbol': '€'}, 'GBP': {'15m': 8866.84, 'last': 8866.84, 'buy': 8866.84, 'sell': 8866.84, 'symbol': '£'}, 'HKD': {'15m': 90027.47, 'last': 90027.47, 'buy': 90027.47, 'sell': 90027.47, 'symbol': '$'}, 'INR': {'15m': 870356.18, 'last': 870356.18, 'buy': 870356.18, 'sell': 870356.18, 'symbol': '₹'}, 'ISK': {'15m': 1601038.9, 'last': 1601038.9, 'buy': 1601038.9, 'sell': 1601038.9, 'symbol': 'kr'}, 'JPY': {'15m': 1231929.44, 'last': 1231929.44, 'buy': 1231929.44, 'sell': 1231929.44, 'symbol': '¥'}, 'KRW': {'15m': 13843360.88, 'last': 13843360.88, 'buy': 13843360.88, 'sell': 13843360.88, 'symbol': '₩'}, 'NZD': {'15m': 17753.7, 'last': 17753.7, 'buy': 17753.7, 'sell': 17753.7, 'symbol': '$'}, 'PLN': {'15m': 43410.94, 'last': 43410.94, 'buy': 43410.94, 'sell': 43410.94, 'symbol': 'zł'}, 'RUB': {'15m': 868955.96, 'last': 868955.96, 'buy': 868955.96, 'sell': 868955.96, 'symbol': 'RUB'}, 'SEK': {'15m': 102017.68, 'last': 102017.68, 'buy': 102017.68, 'sell': 102017.68, 'symbol': 'kr'}, 'SGD': {'15m': 15933.58, 'last': 15933.58, 'buy': 15933.58, 'sell': 15933.58, 'symbol': '$'}, 'THB': {'15m': 366042.0, 'last': 366042.0, 'buy': 366042.0, 'sell': 366042.0, 'symbol': '฿'}, 'TRY': {'15m': 85021.27, 'last': 85021.27, 'buy': 85021.27, 'sell': 85021.27, 'symbol': '₺'}, 'TWD': {'15m': 341550.96, 'last': 341550.96, 'buy': 341550.96, 'sell': 341550.96, 'symbol': 'NT$'}}
{'USD': {'15m': 11616.04, 'last': 11616.04, 'buy': 11616.04, 'sell': 11616.04, 'symbol': '$'}, 'AUD': {'15m': 16205.74, 'last': 16205.74, 'buy': 16205.74, 'sell': 16205.74, 'symbol': '$'}, 'BRL': {'15m': 65301.28, 'last': 65301.28, 'buy': 65301.28, 'sell': 65301.28, 'symbol': 'R$'}, 'CAD': {'15m': 15303.79, 'last': 15303.79, 'buy': 15303.79, 'sell': 15303.79, 'symbol': '$'}, 'CHF': {'15m': 10588.28, 'last': 10588.28, 'buy': 10588.28, 'sell': 10588.28, 'symbol': 'CHF'}, 'CLP': {'15m': 9212683.9, 'last': 9212683.9, 'buy': 9212683.9, 'sell': 9212683.9, 'symbol': '$'}, 'CNY': {'15m': 80377.21, 'last': 80377.21, 'buy': 80377.21, 'sell': 80377.21, 'symbol': '¥'}, 'DKK': {'15m': 73255.41, 'last': 73255.41, 'buy': 73255.41, 'sell': 73255.41, 'symbol': 'kr'}, 'EUR': {'15m': 9864.6, 'last': 9864.6, 'buy': 9864.6, 'sell': 9864.6, 'symbol': '€'}, 'GBP': {'15m': 8866.84, 'last': 8866.84, 'buy': 8866.84, 'sell': 8866.84, 'symbol': '£'}, 'HKD': {'15m': 90027.47, 'last': 90027.47, 'buy': 90027.47, 'sell': 90027.47, 'symbol': '$'}, 'INR': {'15m': 870356.18, 'last': 870356.18, 'buy': 870356.18, 'sell': 870356.18, 'symbol': '₹'}, 'ISK': {'15m': 1601038.9, 'last': 1601038.9, 'buy': 1601038.9, 'sell': 1601038.9, 'symbol': 'kr'}, 'JPY': {'15m': 1231929.44, 'last': 1231929.44, 'buy': 1231929.44, 'sell': 1231929.44, 'symbol': '¥'}, 'KRW': {'15m': 13843360.88, 'last': 13843360.88, 'buy': 13843360.88, 'sell': 13843360.88, 'symbol': '₩'}, 'NZD': {'15m': 17753.7, 'last': 17753.7, 'buy': 17753.7, 'sell': 17753.7, 'symbol': '$'}, 'PLN': {'15m': 43410.94, 'last': 43410.94, 'buy': 43410.94, 'sell': 43410.94, 'symbol': 'zł'}, 'RUB': {'15m': 868955.96, 'last': 868955.96, 'buy': 868955.96, 'sell': 868955.96, 'symbol': 'RUB'}, 'SEK': {'15m': 102017.68, 'last': 102017.68, 'buy': 102017.68, 'sell': 102017.68, 'symbol': 'kr'}, 'SGD': {'15m': 15933.58, 'last': 15933.58, 'buy': 15933.58, 'sell': 15933.58, 'symbol': '$'}, 'THB': {'15m': 366042.0, 'last': 366042.0, 'buy': 366042.0, 'sell': 366042.0, 'symbol': '฿'}, 'TRY': {'15m': 85021.27, 'last': 85021.27, 'buy': 85021.27, 'sell': 85021.27, 'symbol': '₺'}, 'TWD': {'15m': 341550.96, 'last': 341550.96, 'buy': 341550.96, 'sell': 341550.96, 'symbol': 'NT$'}}
{'USD': {'15m': 11616.04, 'last': 11616.04, 'buy': 11616.04, 'sell': 11616.04, 'symbol': '$'}, 'AUD': {'15m': 16205.74, 'last': 16205.74, 'buy': 16205.74, 'sell': 16205.74, 'symbol': '$'}, 'BRL': {'15m': 65301.28, 'last': 65301.28, 'buy': 65301.28, 'sell': 65301.28, 'symbol': 'R$'}, 'CAD': {'15m': 15303.79, 'last': 15303.79, 'buy': 15303.79, 'sell': 15303.79, 'symbol': '$'}, 'CHF': {'15m': 10588.28, 'last': 10588.28, 'buy': 10588.28, 'sell': 10588.28, 'symbol': 'CHF'}, 'CLP': {'15m': 9212683.9, 'last': 9212683.9, 'buy': 9212683.9, 'sell': 9212683.9, 'symbol': '$'}, 'CNY': {'15m': 80377.21, 'last': 80377.21, 'buy': 80377.21, 'sell': 80377.21, 'symbol': '¥'}, 'DKK': {'15m': 73255.41, 'last': 73255.41, 'buy': 73255.41, 'sell': 73255.41, 'symbol': 'kr'}, 'EUR': {'15m': 9864.6, 'last': 9864.6, 'buy': 9864.6, 'sell': 9864.6, 'symbol': '€'}, 'GBP': {'15m': 8866.84, 'last': 8866.84, 'buy': 8866.84, 'sell': 8866.84, 'symbol': '£'}, 'HKD': {'15m': 90027.47, 'last': 90027.47, 'buy': 90027.47, 'sell': 90027.47, 'symbol': '$'}, 'INR': {'15m': 870356.18, 'last': 870356.18, 'buy': 870356.18, 'sell': 870356.18, 'symbol': '₹'}, 'ISK': {'15m': 1601038.9, 'last': 1601038.9, 'buy': 1601038.9, 'sell': 1601038.9, 'symbol': 'kr'}, 'JPY': {'15m': 1231929.44, 'last': 1231929.44, 'buy': 1231929.44, 'sell': 1231929.44, 'symbol': '¥'}, 'KRW': {'15m': 13843360.88, 'last': 13843360.88, 'buy': 13843360.88, 'sell': 13843360.88, 'symbol': '₩'}, 'NZD': {'15m': 17753.7, 'last': 17753.7, 'buy': 17753.7, 'sell': 17753.7, 'symbol': '$'}, 'PLN': {'15m': 43410.94, 'last': 43410.94, 'buy': 43410.94, 'sell': 43410.94, 'symbol': 'zł'}, 'RUB': {'15m': 868955.96, 'last': 868955.96, 'buy': 868955.96, 'sell': 868955.96, 'symbol': 'RUB'}, 'SEK': {'15m': 102017.68, 'last': 102017.68, 'buy': 102017.68, 'sell': 102017.68, 'symbol': 'kr'}, 'SGD': {'15m': 15933.58, 'last': 15933.58, 'buy': 15933.58, 'sell': 15933.58, 'symbol': '$'}, 'THB': {'15m': 366042.0, 'last': 366042.0, 'buy': 366042.0, 'sell': 366042.0, 'symbol': '฿'}, 'TRY': {'15m': 85021.27, 'last': 85021.27, 'buy': 85021.27, 'sell': 85021.27, 'symbol': '₺'}, 'TWD': {'15m': 341550.96, 'last': 341550.96, 'buy': 341550.96, 'sell': 341550.96, 'symbol': 'NT$'}}
{'USD': {'15m': 11616.82, 'last': 11616.82, 'buy': 11616.82, 'sell': 11616.82, 'symbol': '$'}, 'AUD': {'15m': 16204.46, 'last': 16204.46, 'buy': 16204.46, 'sell': 16204.46, 'symbol': '$'}, 'BRL': {'15m': 65305.65, 'last': 65305.65, 'buy': 65305.65, 'sell': 65305.65, 'symbol': 'R$'}, 'CAD': {'15m': 15302.23, 'last': 15302.23, 'buy': 15302.23, 'sell': 15302.23, 'symbol': '$'}, 'CHF': {'15m': 10588.85, 'last': 10588.85, 'buy': 10588.85, 'sell': 10588.85, 'symbol': 'CHF'}, 'CLP': {'15m': 9213275.97, 'last': 9213275.97, 'buy': 9213275.97, 'sell': 9213275.97, 'symbol': '$'}, 'CNY': {'15m': 80382.58, 'last': 80382.58, 'buy': 80382.58, 'sell': 80382.58, 'symbol': '¥'}, 'DKK': {'15m': 73286.28, 'last': 73286.28, 'buy': 73286.28, 'sell': 73286.28, 'symbol': 'kr'}, 'EUR': {'15m': 9865.33, 'last': 9865.33, 'buy': 9865.33, 'sell': 9865.33, 'symbol': '€'}, 'GBP': {'15m': 8868.58, 'last': 8868.58, 'buy': 8868.58, 'sell': 8868.58, 'symbol': '£'}, 'HKD': {'15m': 90033.14, 'last': 90033.14, 'buy': 90033.14, 'sell': 90033.14, 'symbol': '$'}, 'INR': {'15m': 870414.34, 'last': 870414.34, 'buy': 870414.34, 'sell': 870414.34, 'symbol': '₹'}, 'ISK': {'15m': 1601145.91, 'last': 1601145.91, 'buy': 1601145.91, 'sell': 1601145.91, 'symbol': 'kr'}, 'JPY': {'15m': 1231925.29, 'last': 1231925.29, 'buy': 1231925.29, 'sell': 1231925.29, 'symbol': '¥'}, 'KRW': {'15m': 13844286.07, 'last': 13844286.07, 'buy': 13844286.07, 'sell': 13844286.07, 'symbol': '₩'}, 'NZD': {'15m': 17752.53, 'last': 17752.53, 'buy': 17752.53, 'sell': 17752.53, 'symbol': '$'}, 'PLN': {'15m': 43424.56, 'last': 43424.56, 'buy': 43424.56, 'sell': 43424.56, 'symbol': 'zł'}, 'RUB': {'15m': 869014.03, 'last': 869014.03, 'buy': 869014.03, 'sell': 869014.03, 'symbol': 'RUB'}, 'SEK': {'15m': 101821.42, 'last': 101821.42, 'buy': 101821.42, 'sell': 101821.42, 'symbol': 'kr'}, 'SGD': {'15m': 15935.16, 'last': 15935.16, 'buy': 15935.16, 'sell': 15935.16, 'symbol': '$'}, 'THB': {'15m': 366204.5, 'last': 366204.5, 'buy': 366204.5, 'sell': 366204.5, 'symbol': '฿'}, 'TRY': {'15m': 85170.95, 'last': 85170.95, 'buy': 85170.95, 'sell': 85170.95, 'symbol': '₺'}, 'TWD': {'15m': 341573.79, 'last': 341573.79, 'buy': 341573.79, 'sell': 341573.79, 'symbol': 'NT$'}}
{'USD': {'15m': 11616.04, 'last': 11616.04, 'buy': 11616.04, 'sell': 11616.04, 'symbol': '$'}, 'AUD': {'15m': 16205.74, 'last': 16205.74, 'buy': 16205.74, 'sell': 16205.74, 'symbol': '$'}, 'BRL': {'15m': 65301.28, 'last': 65301.28, 'buy': 65301.28, 'sell': 65301.28, 'symbol': 'R$'}, 'CAD': {'15m': 15303.79, 'last': 15303.79, 'buy': 15303.79, 'sell': 15303.79, 'symbol': '$'}, 'CHF': {'15m': 10588.28, 'last': 10588.28, 'buy': 10588.28, 'sell': 10588.28, 'symbol': 'CHF'}, 'CLP': {'15m': 9212683.9, 'last': 9212683.9, 'buy': 9212683.9, 'sell': 9212683.9, 'symbol': '$'}, 'CNY': {'15m': 80377.21, 'last': 80377.21, 'buy': 80377.21, 'sell': 80377.21, 'symbol': '¥'}, 'DKK': {'15m': 73255.41, 'last': 73255.41, 'buy': 73255.41, 'sell': 73255.41, 'symbol': 'kr'}, 'EUR': {'15m': 9864.6, 'last': 9864.6, 'buy': 9864.6, 'sell': 9864.6, 'symbol': '€'}, 'GBP': {'15m': 8866.84, 'last': 8866.84, 'buy': 8866.84, 'sell': 8866.84, 'symbol': '£'}, 'HKD': {'15m': 90027.47, 'last': 90027.47, 'buy': 90027.47, 'sell': 90027.47, 'symbol': '$'}, 'INR': {'15m': 870356.18, 'last': 870356.18, 'buy': 870356.18, 'sell': 870356.18, 'symbol': '₹'}, 'ISK': {'15m': 1601038.9, 'last': 1601038.9, 'buy': 1601038.9, 'sell': 1601038.9, 'symbol': 'kr'}, 'JPY': {'15m': 1231929.44, 'last': 1231929.44, 'buy': 1231929.44, 'sell': 1231929.44, 'symbol': '¥'}, 'KRW': {'15m': 13843360.88, 'last': 13843360.88, 'buy': 13843360.88, 'sell': 13843360.88, 'symbol': '₩'}, 'NZD': {'15m': 17753.7, 'last': 17753.7, 'buy': 17753.7, 'sell': 17753.7, 'symbol': '$'}, 'PLN': {'15m': 43410.94, 'last': 43410.94, 'buy': 43410.94, 'sell': 43410.94, 'symbol': 'zł'}, 'RUB': {'15m': 868955.96, 'last': 868955.96, 'buy': 868955.96, 'sell': 868955.96, 'symbol': 'RUB'}, 'SEK': {'15m': 102017.68, 'last': 102017.68, 'buy': 102017.68, 'sell': 102017.68, 'symbol': 'kr'}, 'SGD': {'15m': 15933.58, 'last': 15933.58, 'buy': 15933.58, 'sell': 15933.58, 'symbol': '$'}, 'THB': {'15m': 366042.0, 'last': 366042.0, 'buy': 366042.0, 'sell': 366042.0, 'symbol': '฿'}, 'TRY': {'15m': 85021.27, 'last': 85021.27, 'buy': 85021.27, 'sell': 85021.27, 'symbol': '₺'}, 'TWD': {'15m': 341550.96, 'last': 341550.96, 'buy': 341550.96, 'sell': 341550.96, 'symbol': 'NT$'}}
{'USD': {'15m': 11616.04, 'last': 11616.04, 'buy': 11616.04, 'sell': 11616.04, 'symbol': '$'}, 'AUD': {'15m': 16205.74, 'last': 16205.74, 'buy': 16205.74, 'sell': 16205.74, 'symbol': '$'}, 'BRL': {'15m': 65301.28, 'last': 65301.28, 'buy': 65301.28, 'sell': 65301.28, 'symbol': 'R$'}, 'CAD': {'15m': 15303.79, 'last': 15303.79, 'buy': 15303.79, 'sell': 15303.79, 'symbol': '$'}, 'CHF': {'15m': 10588.28, 'last': 10588.28, 'buy': 10588.28, 'sell': 10588.28, 'symbol': 'CHF'}, 'CLP': {'15m': 9212683.9, 'last': 9212683.9, 'buy': 9212683.9, 'sell': 9212683.9, 'symbol': '$'}, 'CNY': {'15m': 80377.21, 'last': 80377.21, 'buy': 80377.21, 'sell': 80377.21, 'symbol': '¥'}, 'DKK': {'15m': 73255.41, 'last': 73255.41, 'buy': 73255.41, 'sell': 73255.41, 'symbol': 'kr'}, 'EUR': {'15m': 9864.6, 'last': 9864.6, 'buy': 9864.6, 'sell': 9864.6, 'symbol': '€'}, 'GBP': {'15m': 8866.84, 'last': 8866.84, 'buy': 8866.84, 'sell': 8866.84, 'symbol': '£'}, 'HKD': {'15m': 90027.47, 'last': 90027.47, 'buy': 90027.47, 'sell': 90027.47, 'symbol': '$'}, 'INR': {'15m': 870356.18, 'last': 870356.18, 'buy': 870356.18, 'sell': 870356.18, 'symbol': '₹'}, 'ISK': {'15m': 1601038.9, 'last': 1601038.9, 'buy': 1601038.9, 'sell': 1601038.9, 'symbol': 'kr'}, 'JPY': {'15m': 1231929.44, 'last': 1231929.44, 'buy': 1231929.44, 'sell': 1231929.44, 'symbol': '¥'}, 'KRW': {'15m': 13843360.88, 'last': 13843360.88, 'buy': 13843360.88, 'sell': 13843360.88, 'symbol': '₩'}, 'NZD': {'15m': 17753.7, 'last': 17753.7, 'buy': 17753.7, 'sell': 17753.7, 'symbol': '$'}, 'PLN': {'15m': 43410.94, 'last': 43410.94, 'buy': 43410.94, 'sell': 43410.94, 'symbol': 'zł'}, 'RUB': {'15m': 868955.96, 'last': 868955.96, 'buy': 868955.96, 'sell': 868955.96, 'symbol': 'RUB'}, 'SEK': {'15m': 102017.68, 'last': 102017.68, 'buy': 102017.68, 'sell': 102017.68, 'symbol': 'kr'}, 'SGD': {'15m': 15933.58, 'last': 15933.58, 'buy': 15933.58, 'sell': 15933.58, 'symbol': '$'}, 'THB': {'15m': 366042.0, 'last': 366042.0, 'buy': 366042.0, 'sell': 366042.0, 'symbol': '฿'}, 'TRY': {'15m': 85021.27, 'last': 85021.27, 'buy': 85021.27, 'sell': 85021.27, 'symbol': '₺'}, 'TWD': {'15m': 341550.96, 'last': 341550.96, 'buy': 341550.96, 'sell': 341550.96, 'symbol': 'NT$'}}
{'USD': {'15m': 11616.04, 'last': 11616.04, 'buy': 11616.04, 'sell': 11616.04, 'symbol': '$'}, 'AUD': {'15m': 16205.74, 'last': 16205.74, 'buy': 16205.74, 'sell': 16205.74, 'symbol': '$'}, 'BRL': {'15m': 65301.28, 'last': 65301.28, 'buy': 65301.28, 'sell': 65301.28, 'symbol': 'R$'}, 'CAD': {'15m': 15303.79, 'last': 15303.79, 'buy': 15303.79, 'sell': 15303.79, 'symbol': '$'}, 'CHF': {'15m': 10588.28, 'last': 10588.28, 'buy': 10588.28, 'sell': 10588.28, 'symbol': 'CHF'}, 'CLP': {'15m': 9212683.9, 'last': 9212683.9, 'buy': 9212683.9, 'sell': 9212683.9, 'symbol': '$'}, 'CNY': {'15m': 80377.21, 'last': 80377.21, 'buy': 80377.21, 'sell': 80377.21, 'symbol': '¥'}, 'DKK': {'15m': 73255.41, 'last': 73255.41, 'buy': 73255.41, 'sell': 73255.41, 'symbol': 'kr'}, 'EUR': {'15m': 9864.6, 'last': 9864.6, 'buy': 9864.6, 'sell': 9864.6, 'symbol': '€'}, 'GBP': {'15m': 8866.84, 'last': 8866.84, 'buy': 8866.84, 'sell': 8866.84, 'symbol': '£'}, 'HKD': {'15m': 90027.47, 'last': 90027.47, 'buy': 90027.47, 'sell': 90027.47, 'symbol': '$'}, 'INR': {'15m': 870356.18, 'last': 870356.18, 'buy': 870356.18, 'sell': 870356.18, 'symbol': '₹'}, 'ISK': {'15m': 1601038.9, 'last': 1601038.9, 'buy': 1601038.9, 'sell': 1601038.9, 'symbol': 'kr'}, 'JPY': {'15m': 1231929.44, 'last': 1231929.44, 'buy': 1231929.44, 'sell': 1231929.44, 'symbol': '¥'}, 'KRW': {'15m': 13843360.88, 'last': 13843360.88, 'buy': 13843360.88, 'sell': 13843360.88, 'symbol': '₩'}, 'NZD': {'15m': 17753.7, 'last': 17753.7, 'buy': 17753.7, 'sell': 17753.7, 'symbol': '$'}, 'PLN': {'15m': 43410.94, 'last': 43410.94, 'buy': 43410.94, 'sell': 43410.94, 'symbol': 'zł'}, 'RUB': {'15m': 868955.96, 'last': 868955.96, 'buy': 868955.96, 'sell': 868955.96, 'symbol': 'RUB'}, 'SEK': {'15m': 102017.68, 'last': 102017.68, 'buy': 102017.68, 'sell': 102017.68, 'symbol': 'kr'}, 'SGD': {'15m': 15933.58, 'last': 15933.58, 'buy': 15933.58, 'sell': 15933.58, 'symbol': '$'}, 'THB': {'15m': 366042.0, 'last': 366042.0, 'buy': 366042.0, 'sell': 366042.0, 'symbol': '฿'}, 'TRY': {'15m': 85021.27, 'last': 85021.27, 'buy': 85021.27, 'sell': 85021.27, 'symbol': '₺'}, 'TWD': {'15m': 341550.96, 'last': 341550.96, 'buy': 341550.96, 'sell': 341550.96, 'symbol': 'NT$'}}

Program interrupted. (Use 'cont' to resume).
> d:\python38\lib\threading.py(309)wait()
-> return gotit
(Pdb)
```

**Comment by Voyz** [comment]
That's fantastic news!! I'm happy we managed to find the culprit (and a few others along the lines!). And most importantly I'm happy you can run that example finally 😊 Thanks for doing all these tests mate, that's been a massive help!

I'll create a PR with the `Event loop...` fix, while the unicode encoding workaround I'll put into a Troubleshooting section (which doesn't yet exist). I'll do more research into the PYTHONENCODING and why and when it is needed. Any idea if you machine had this set to something different for some reason? 

I'm also looking into fixing the exception logging that has failed you here and prevented you from seeing the right message  straight away.

I'll keep you posted on updates on these issues. In the meantime I'm modifying the title of this Issue so that it's easier to find info on our hunt for the Unicode error, in case others stumble upon it in the future too.

Well done and thanks a lot!

**Comment by Voyz** [comment]
Sorry just realised you mentioned you'd like to contribute - would you like to introduce the PR with the `Event loop...` fix? I'm more than happy to do it otherwise, but just thought it would be great for you to have a contribution too, seeing you mentioned you'd like to do so. Either way is good for me 👍

**Comment by pybokeh** [comment]
@Voyz You're welcome!  It was fun and rewarding for me to help in any way I can.  

As for the PYTHONIOENCODING thing, I have no idea.  I think it has to do with whenever things are being echoed or printed to standard output?  or what about to file?  I do want to test your other examples where we are sending output to file.

Thanks for asking me to do the PR.  But, it's ok,, please do the PR yourself.  I'm just glad to be able to help out.

**Comment by Voyz** [comment]
Either way I'm happy that it helped. 

It seems like it would break for a file too. I'm also guessing that this possibly was also breaking the exceptions - although that's just a blind guess - so it could be both stdout and stderr that are affected by it. From what I read on the `UnicodeEncodeError` this should also cause problems if you write to a file. Easy way to verify it would be to run the following two snippets without that `set PYTHONIOENCODING=utf-8` env variable (so the old way).

```python
print('₹')
````

and

```python
with open('unicode_test_file.txt', 'a') as f:
    f.write('₹')
```

Both should break as far as I understand. I'll let you know if I figure out why your setup might have had that set incorrectly. And I'd love to hear how it goes with other examples for you, so keep me posted 😊

Naturally, I'll do the PR, no worries - you helped out big time. Thanks for all the contribution towards fixing this problem!

**Comment by Voyz** [comment]
Good news - I managed to get to the bottom of this. There was indeed a bug in exception logging of APSPlanner, triggered by exceptions with a strange signature such as that of UnicodeEncodeError. My bad. Got that verified and fixed now.

Most importantly - I finally found a way to reproduce this error! And not without struggle - there's a million methods to fix it out there, just about none to reproduce it. Eventually, this is what was needed:

```
set PYTHONIOENCODING=windows-1252
set PYTHONLEGACYWINDOWSSTDIO=windows-1252
```

or alternatively in code:

```
sys.stdin.reconfigure(encoding='windows-1252')
sys.stdout.reconfigure(encoding='windows-1252')
```

Which would suggest that your machine had it set to `windows-1252` (or something else?) by default.  A good way to find out what's the answer is to run:
```
print(sys.stdin.encoding, sys.stdout.encoding)
```

Either way - happy I managed to reproduce what was happening on your end finally. Thanks for the patience once again! I'll update when the fixes are released.

**Comment by pybokeh** [comment]
@Voyz I found out what my problem was.  I had looked at my local environment variables before, but overlooked that there is a ```PYTHONLEGACYWINDOWSSTDIO``` that was set to true.  After removing this environment variable, rebooting my machine, now I can run your examples without having to set PYTHONIOENCODING environment variable.  I am trying to recall the reasoning for why I had ```PYTHONLEGACYWINDOWSSTDIO``` environment variable set.  I'm guessing it was due to when I was using older versions of Python and had encoding issues with the default Windows terminal back then.  Official Python docs happen to have a [page](https://docs.python.org/3/using/cmdline.html) on the command line and it appears there was some kind of change beginning with Python 3.6 where that environment variable was no longer needed.

With no Python-related environment set and then executing ```print(sys.stdin.encoding, sys.stdout.encoding)```, I am getting utf-8 now.

**Comment by Voyz** [comment]
Fantastic you managed to figure this one out! Thanks for following up with the explanation - that explains everything. I nonetheless added a warning should someone have that encoding set incorrectly, as this may cause unexpected behaviour without being very verbose.
